travis:
  secure:
    BINSTAR_TOKEN: lFFBL6zJ+hTZxsaUWDMzTo3PrHWcqO6X53+prmqkXtpqZ+TMSiFU0Em7H/4GO3yYmPS8xc2iG6PquAxP/jkzFMM+vYOTgUWK5oUhdlHtBAbCPfW5T43S160y9V+OezhEIinT49XE+Vcay6mGzUXfsl/I0w8RB28KYld3E019Q6EsClfFQOPyAHqCE4gAJRfA1BEi784N11lOcY5yWjShXNAVyhTY8pU33B4WEkqZ1Bp6u8PBnzosRBKJG2I5GAFGsCTA0x5DKQlFWriRay9r9gmDhIP2aiipQ/rOHDvkZRBX0ADlz4bQfuLqxZwNPZcmBG2WyK4CXEEw0TJYZy7g3JlSrj1RGUx0BAfHb1H36pkbprVUucKZZ8VadIbeT4Y9Z7u5tD71Ijnji0FDoF/34/2IM4LNIg8XsMjhh6SHJkPqf3LX+bpI7NcFFtWz7uLiEuv8akmONXsB8LBtBFszwGjDhnmpv7XrwwAmfd3TF3r9yZKwSqKNfoDW07XxqfFe/V2S707TtdN899Tjg+GfjVevWweurXrX69AZIgNEyVGcE03qLMXRgZU7V/mi1QiPFZhleJ4nQLB7iuVhlaVvH+vX1P/cduLqskLVQcK8S3Od/LVsITQjWdSLWtDaqySW4gGws4SNYmDPAt7MulndNVvXbYvasaQMtHW9GE2S020=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
