travis:
  secure:
    BINSTAR_TOKEN: cC+yy3X4r+poJ2oNFiqCTrQRFmjvvA6EPjEjNkhpmIO5MpqH36XVIIYnTQvZU1FwxPdCPuHACqWrJ0JMHHBfHBFr2PbTE2NyJG+Lxxzd3oULUo05nCk1S+j0I+F554GrquyekxHrFZ2WW5sP3YvR4ak0s0XjnHmE4fgnxfVUZJql5FIA67doj4dx/PxZpDBv/ZjThIda8pLMDaXpI18r12p3XeTX32giWnvkI6+nahQqww0HXNF82+uWYzYYcApOJZTcqfK9gBIyCpU3f1MN47IO3/imVH8JhmgW/GOvqm8OqEIcUdf7bNauJNXaauw+7OlscbPBckDH0Z6u4A4Gri+R+drao+xRJ7FKPidfq4Rp4GPTuedS6iNLDOkLbgsCltL4YiF4rrAXeONDusNl1bfvV8jCZ1+bx+uKQo0S8kzxj290GPtzMhcrlNqSspjXo5tLQlbRPUnZX2E3UDYCg0ksaknbQMdSN52t/i45kcf5JLgX+6aedA51OWFt7R3MOxdJVbkcjtQnbSvlAyHoi0eg5vZimitdw7t5sbbWZAlbYdOvGFFQ05AnpmWRqM693xr8WlyEwR+fvCfKnbboQbjIdZNgL7YFRI4JDIDA11eZg+jeB5kio7CWfhLna1fWGWZwAVevTIhO3qsYYLH1uS25Io28VsFQPJyqOI7NSVY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
